"""
Example script demonstrating how to use the report generation module

This script shows how to:
1. Generate signal analysis reports
2. Generate backtest results reports
3. Generate portfolio performance reports
4. Customize report configuration

Author: BIST AI Trading System
Date: 2025-11-16
"""

import sys
import os
from datetime import datetime

# Add parent directory to path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

import numpy as np
from src.ui.reports import (
    generate_html_signal_report,
    generate_pdf_signal_report,
    generate_html_backtest_report,
    generate_pdf_backtest_report,
    generate_html_portfolio_report,
    generate_pdf_portfolio_report,
    ReportConfig,
    PDFReportGenerator,
    HTMLReportGenerator
)


def example_signal_report():
    """Example: Generate signal analysis report"""
    print("\n" + "="*80)
    print("EXAMPLE 1: SIGNAL ANALYSIS REPORT")
    print("="*80)

    # Sample signals (as would be generated by SignalGenerator)
    signals = [
        {
            'stock_code': 'THYAO',
            'signal': 'STRONG_BUY',
            'confidence': 'HIGH',
            'confidence_score': 0.85,
            'current_price': 260.0,
            'target_price': 275.0,
            'expected_return': 0.0577,
            'position_size': 0.12,
            'risk_score': 0.35,
            'stop_loss': 245.0,
            'take_profit': 285.0,
            'rationale': 'Strong institutional buying detected. Positive news sentiment. Technical breakout confirmed.'
        },
        {
            'stock_code': 'GARAN',
            'signal': 'BUY',
            'confidence': 'MEDIUM',
            'confidence_score': 0.72,
            'current_price': 88.5,
            'target_price': 92.0,
            'expected_return': 0.0395,
            'position_size': 0.08,
            'risk_score': 0.42,
            'stop_loss': 84.0,
            'take_profit': 95.0,
            'rationale': 'Positive fundamentals. Moderate whale activity. Good risk/reward ratio.'
        },
        {
            'stock_code': 'EREGL',
            'signal': 'HOLD',
            'confidence': 'MEDIUM',
            'confidence_score': 0.55,
            'current_price': 44.2,
            'target_price': 45.0,
            'expected_return': 0.0181,
            'position_size': 0.00,
            'risk_score': 0.58,
            'stop_loss': None,
            'take_profit': None,
            'rationale': 'Mixed signals from models. High volatility. Waiting for clearer direction.'
        },
        {
            'stock_code': 'KCHOL',
            'signal': 'BUY',
            'confidence': 'HIGH',
            'confidence_score': 0.78,
            'current_price': 125.0,
            'target_price': 132.5,
            'expected_return': 0.06,
            'position_size': 0.10,
            'risk_score': 0.38,
            'stop_loss': 118.0,
            'take_profit': 135.0,
            'rationale': 'Strong earnings report. Positive sector outlook. Technical indicators aligned.'
        },
        {
            'stock_code': 'AKBNK',
            'signal': 'SELL',
            'confidence': 'MEDIUM',
            'confidence_score': 0.65,
            'current_price': 52.0,
            'target_price': 48.5,
            'expected_return': -0.0673,
            'position_size': 0.00,
            'risk_score': 0.50,
            'stop_loss': 54.5,
            'take_profit': 47.0,
            'rationale': 'Negative sentiment from news analysis. Profit taking by institutions.'
        }
    ]

    # Generate HTML report
    print("\nGenerating HTML signal report...")
    generate_html_signal_report(
        signals=signals,
        output_path='output/signal_analysis_report.html',
        metadata={
            'timeframe': '30 minutes',
            'generation_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'market_condition': 'Volatile',
            'index_level': 'BIST100: 8,456.32'
        }
    )
    print("✓ HTML report saved: output/signal_analysis_report.html")

    # Generate PDF report
    print("\nGenerating PDF signal report...")
    try:
        generate_pdf_signal_report(
            signals=signals,
            output_path='output/signal_analysis_report.pdf',
            metadata={
                'timeframe': '30 minutes',
                'generation_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'market_condition': 'Volatile'
            }
        )
        print("✓ PDF report saved: output/signal_analysis_report.pdf")
    except ImportError as e:
        print(f"⚠ PDF generation skipped: {e}")


def example_backtest_report():
    """Example: Generate backtest results report"""
    print("\n" + "="*80)
    print("EXAMPLE 2: BACKTEST RESULTS REPORT")
    print("="*80)

    # Simulate backtest results
    np.random.seed(42)
    n_trades = 200

    # Generate realistic returns (slightly profitable strategy)
    winning_returns = np.random.normal(0.025, 0.015, int(n_trades * 0.58))
    losing_returns = np.random.normal(-0.018, 0.012, int(n_trades * 0.42))
    returns = np.concatenate([winning_returns, losing_returns])
    np.random.shuffle(returns)

    # Generate equity curve
    initial_capital = 100000
    equity_curve = [initial_capital]
    for ret in returns:
        equity_curve.append(equity_curve[-1] * (1 + ret))

    # Calculate metrics
    equity_array = np.array(equity_curve)
    running_max = np.maximum.accumulate(equity_array)
    drawdown = (equity_array - running_max) / running_max
    max_drawdown = abs(np.min(drawdown))

    total_return = (equity_curve[-1] - initial_capital) / initial_capital
    annualized_return = ((1 + total_return) ** (252 / len(returns))) - 1

    winning_trades = int(np.sum(returns > 0))
    losing_trades = int(np.sum(returns < 0))
    win_rate = (winning_trades / len(returns)) * 100

    avg_win = np.mean(returns[returns > 0])
    avg_loss = np.mean(returns[returns < 0])

    sharpe_ratio = (np.mean(returns) - 0) / np.std(returns) * np.sqrt(252)

    # Sortino ratio (downside deviation)
    downside_returns = returns[returns < 0]
    downside_std = np.sqrt(np.mean(downside_returns ** 2))
    sortino_ratio = (np.mean(returns) - 0) / downside_std * np.sqrt(252)

    profit_factor = abs(np.sum(returns[returns > 0]) / np.sum(returns[returns < 0]))

    backtest_results = {
        'metrics': {
            'win_rate': win_rate,
            'total_trades': len(returns),
            'winning_trades': winning_trades,
            'losing_trades': losing_trades,
            'sharpe_ratio': sharpe_ratio,
            'sortino_ratio': sortino_ratio,
            'calmar_ratio': annualized_return / max_drawdown if max_drawdown > 0 else 0,
            'max_drawdown': max_drawdown,
            'max_drawdown_pct': max_drawdown * 100,
            'total_return': total_return,
            'total_return_pct': total_return * 100,
            'annualized_return': annualized_return,
            'annualized_volatility': np.std(returns) * np.sqrt(252),
            'profit_factor': profit_factor,
            'avg_winning_trade': avg_win,
            'avg_losing_trade': avg_loss,
            'largest_win': np.max(returns),
            'largest_loss': np.min(returns),
            'expectancy': np.mean(returns),
            'risk_reward_ratio': abs(avg_win / avg_loss)
        },
        'equity_curve': equity_curve,
        'returns': returns.tolist()
    }

    # Generate HTML report
    print("\nGenerating HTML backtest report...")
    generate_html_backtest_report(
        backtest_results=backtest_results,
        output_path='output/backtest_results_report.html',
        metadata={
            'strategy': 'ML Signal Following Strategy',
            'period': '2023-01-01 to 2025-11-16',
            'initial_capital': f'{initial_capital:,} TRY',
            'final_capital': f'{equity_curve[-1]:,.2f} TRY',
            'commission': '0.15%'
        }
    )
    print("✓ HTML report saved: output/backtest_results_report.html")

    # Generate PDF report
    print("\nGenerating PDF backtest report...")
    try:
        generate_pdf_backtest_report(
            backtest_results=backtest_results,
            output_path='output/backtest_results_report.pdf',
            metadata={
                'strategy': 'ML Signal Following Strategy',
                'period': '2023-01-01 to 2025-11-16',
                'initial_capital': f'{initial_capital:,} TRY'
            }
        )
        print("✓ PDF report saved: output/backtest_results_report.pdf")
    except ImportError as e:
        print(f"⚠ PDF generation skipped: {e}")


def example_portfolio_report():
    """Example: Generate portfolio performance report"""
    print("\n" + "="*80)
    print("EXAMPLE 3: PORTFOLIO PERFORMANCE REPORT")
    print("="*80)

    # Sample portfolio data (as would come from PortfolioManager)
    portfolio_data = {
        'portfolio_name': 'BIST Trading Portfolio',
        'currency': 'TRY',
        'total_value': 127500.50,
        'cash': 17500.50,
        'positions_value': 110000.00,
        'total_cost_basis': 95000.00,
        'num_positions': 6,
        'unrealized_pnl': 15000.00,
        'realized_pnl': 7500.00,
        'total_pnl': 22500.00,
        'total_commissions': 450.00,
        'initial_cash': 100000.00,
        'total_return_pct': 27.50,
        'last_updated': datetime.now().isoformat(),
        'positions': [
            {
                'symbol': 'THYAO',
                'shares': 100,
                'cost_basis': 250.00,
                'current_price': 265.00,
                'market_value': 26500.00,
                'total_cost': 25000.00,
                'unrealized_pnl': 1500.00,
                'unrealized_pnl_pct': 6.00
            },
            {
                'symbol': 'GARAN',
                'shares': 200,
                'cost_basis': 85.00,
                'current_price': 90.00,
                'market_value': 18000.00,
                'total_cost': 17000.00,
                'unrealized_pnl': 1000.00,
                'unrealized_pnl_pct': 5.88
            },
            {
                'symbol': 'KCHOL',
                'shares': 150,
                'cost_basis': 120.00,
                'current_price': 128.00,
                'market_value': 19200.00,
                'total_cost': 18000.00,
                'unrealized_pnl': 1200.00,
                'unrealized_pnl_pct': 6.67
            },
            {
                'symbol': 'EREGL',
                'shares': 300,
                'cost_basis': 42.00,
                'current_price': 44.50,
                'market_value': 13350.00,
                'total_cost': 12600.00,
                'unrealized_pnl': 750.00,
                'unrealized_pnl_pct': 5.95
            },
            {
                'symbol': 'AKBNK',
                'shares': 400,
                'cost_basis': 48.00,
                'current_price': 52.00,
                'market_value': 20800.00,
                'total_cost': 19200.00,
                'unrealized_pnl': 1600.00,
                'unrealized_pnl_pct': 8.33
            },
            {
                'symbol': 'SISE',
                'shares': 250,
                'cost_basis': 12.00,
                'current_price': 12.60,
                'market_value': 3150.00,
                'total_cost': 3000.00,
                'unrealized_pnl': 150.00,
                'unrealized_pnl_pct': 5.00
            }
        ]
    }

    # Generate HTML report
    print("\nGenerating HTML portfolio report...")
    generate_html_portfolio_report(
        portfolio_data=portfolio_data,
        output_path='output/portfolio_performance_report.html',
        metadata={
            'report_date': datetime.now().strftime('%Y-%m-%d'),
            'account_type': 'Individual Trading Account',
            'risk_profile': 'Moderate'
        }
    )
    print("✓ HTML report saved: output/portfolio_performance_report.html")

    # Generate PDF report
    print("\nGenerating PDF portfolio report...")
    try:
        generate_pdf_portfolio_report(
            portfolio_data=portfolio_data,
            output_path='output/portfolio_performance_report.pdf',
            metadata={
                'report_date': datetime.now().strftime('%Y-%m-%d'),
                'account_type': 'Individual Trading Account'
            }
        )
        print("✓ PDF report saved: output/portfolio_performance_report.pdf")
    except ImportError as e:
        print(f"⚠ PDF generation skipped: {e}")


def example_custom_configuration():
    """Example: Using custom report configuration"""
    print("\n" + "="*80)
    print("EXAMPLE 4: CUSTOM REPORT CONFIGURATION")
    print("="*80)

    # Create custom configuration
    config = ReportConfig(
        title="BIST AI Trading System - Custom Report",
        author="Trading Team",
        subject="Weekly Trading Analysis",
        page_size="A4",
        include_charts=True,
        include_metadata=True
    )

    # Sample data
    signals = [
        {
            'stock_code': 'THYAO',
            'signal': 'STRONG_BUY',
            'confidence_score': 0.88,
            'target_price': 280.0,
            'expected_return': 0.06,
            'rationale': 'All indicators aligned for strong buy'
        }
    ]

    # Generate report with custom config
    print("\nGenerating custom configured report...")
    generator = HTMLReportGenerator(config)
    generator.generate_signal_report(
        signals=signals,
        output_path='output/custom_report.html',
        metadata={
            'custom_field': 'Custom Value',
            'report_type': 'Weekly Analysis'
        }
    )
    print("✓ Custom HTML report saved: output/custom_report.html")


def main():
    """Run all examples"""
    print("\n" + "="*80)
    print("BIST AI TRADING SYSTEM - REPORT GENERATION EXAMPLES")
    print("="*80)

    # Create output directory
    os.makedirs('output', exist_ok=True)

    # Run examples
    example_signal_report()
    example_backtest_report()
    example_portfolio_report()
    example_custom_configuration()

    print("\n" + "="*80)
    print("ALL EXAMPLES COMPLETED SUCCESSFULLY!")
    print("="*80)
    print("\nGenerated files:")
    print("  - output/signal_analysis_report.html")
    print("  - output/signal_analysis_report.pdf (if reportlab installed)")
    print("  - output/backtest_results_report.html")
    print("  - output/backtest_results_report.pdf (if reportlab installed)")
    print("  - output/portfolio_performance_report.html")
    print("  - output/portfolio_performance_report.pdf (if reportlab installed)")
    print("  - output/custom_report.html")
    print("\nOpen these files in your browser to view the reports!")
    print("="*80 + "\n")


if __name__ == "__main__":
    main()
